# Generated by Django 3.1.2 on 2020-11-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseTitle',
            new_name='course_title',
        ),
    ]
