# Generated by Django 3.1.2 on 2020-11-20 12:38

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20201119_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('icon_label', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, null=True)),
                ('image', models.FileField(null=True, upload_to='course-image')),
                ('course_title', models.CharField(max_length=200, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='course desc')),
                ('short_desc', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('course_level', models.CharField(choices=[('F', 'Free'), ('P', 'pro')], max_length=200, null=True)),
                ('status', models.CharField(choices=[('0', 'save to Draft'), ('1', 'Publish')], max_length=200, null=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.topics')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
