# Generated by Django 3.1.2 on 2020-11-20 14:10

from django.conf import settings
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20201120_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='created_on',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='courses',
            name='student',
            field=models.ManyToManyField(related_name='Enrolled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
