# Generated by Django 3.1.2 on 2020-11-20 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20201120_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='student',
            field=models.ManyToManyField(related_name='Enrolled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
