# Generated by Django 3.1.2 on 2020-12-13 10:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20201213_1023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyCourse',
            new_name='CourseOrder',
        ),
    ]
