# Generated by Django 3.1.2 on 2020-12-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201213_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_title',
            new_name='title',
        ),
    ]
