# Generated by Django 3.1.2 on 2020-12-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201214_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='quantity',
        ),
    ]
