# Generated by Django 3.1.2 on 2020-12-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_billingaddress_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='region',
            field=models.CharField(choices=[('Mw', 'Mwanza'), ('Dar', 'Dar es salaam'), ('Ar', 'Arusha'), ('Mb', 'Mbeya')], max_length=10, null=True),
        ),
    ]
