# Generated by Django 3.1.2 on 2020-11-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='link1',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='link2',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='link3',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='link4',
            new_name='tweeter',
        ),
    ]
